### ISSUE TITLE
Translate into Chinese 

### ISSUE THREAD

**Issue by node** [todogroup/osposurvey#116]
As the discussion of this issue https://github.com/todogroup/todogroup.org/issues/378 , we start a Chinese tranlastion project in LFAPAC Open Evangel SIG .

Cloud we use this file as origin English version ?    https://github.com/todogroup/osposurvey/blob/main/2023/questions.md 

@anajsana

**Comment by anajsana** [comment]
Hey @node thank you so much for leading this effort and kudos to LFAPAC Open Evangel SIG team ❤️ 

> Cloud we use this file as origin English version ? https://github.com/todogroup/osposurvey/blob/main/2023/questions.md

The questions are the ones that appear in the [markdown English questionnaire](https://github.com/todogroup/osposurvey/blob/main/2023/questions.md). However, in order to directly load the file translation into Survey Monkey (the tool used to share the survey), we use .CSV or .PO files to import translations into the system.

I've sent you an email with a template in these two formats attached for the community to work on the translation. Once finished, save them under a new name and send them back to me. I'll share them with the research team to load the files into Survey Monkey and generate the survey link 👍 

Additionally, I you want to submit a PR in the /osposurvey repo with a translated version of the [markdown English questionnaire](https://github.com/todogroup/osposurvey/blob/main/2023/questions.md), please do and I'll review and merge it ASAP 💚

Again, thank you so much for all your efforts and contributions to the community 🙏 Please let me know if you need any help!

**Comment by node** [comment]
OK. Let's track by the following task list:

- [ ] translate [markdown file](https://github.com/todogroup/osposurvey/blob/main/2023/questions.md) then submit a PR here 
    - [ ]  split file to several tasks  (in LFAPAC Open Evangel SIG translation repos)
    - [ ]  assign, translate and review 
    - [ ]  merge into one markdown file 
    - [ ]  submit PR here 
- [ ] Use the above result to translate .CSV file (attachment in your mail) then send back to you 


We will update here.

**Comment by node** [comment]
Submit pr #117

**Comment by node** [comment]
Hi @anajsana  Is it necessary to continue send a .CSV file back to you now ? I know the survey has closed this year .

**Comment by anajsana** [comment]
we will have it open until Monday next week. if you already have the CSV completed, please send it to me to add it 👍 if not, it's fine not to send it 🙂

**Comment by node** [comment]
Got it. Let's make it again next year  😄
